version: '3.9'

services:
  libreria-app:
    image: libreria-app
    container_name: LibreriaApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - h2_data:/app/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/libreria_db
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  h2_data:
